In [4]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

iris = load_iris(as_frame=True)

X = iris.data
y = iris.target
target_names = iris.target_names

display(X.head())
display(y.head())
print("features shape:", X.shape)
print("classes name:", target_names)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

print("train data:", X_train.shape, "test data:", X_test.shape)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

acc = accuracy_score(y_test, y_pred)
print(f"accuracy: {acc:.3f}")

cm = confusion_matrix(y_test, y_pred, labels=np.unique(y))
print("Confusion Matrix (raw):\n", cm)

index_names = [f"true_{name}" for name in target_names]
column_names = [f"pred_{name}" for name in target_names]

cm_df = pd.DataFrame(cm, index=index_names, columns=column_names)

print("\nConfusion matrix (as DataFrame):")
display(cm_df)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

features shape: (150, 4)
classes name: ['setosa' 'versicolor' 'virginica']
train data: (112, 4) test data: (38, 4)
accuracy: 0.974
Confusion Matrix (raw):
 [[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]

Confusion matrix (as DataFrame):


pred_setosa  pred_versicolor  pred_virginica
true_setosa               12                0               0
true_versicolor            0               13               0
true_virginica             0                1              12